version: "3"

services:

  web:
    build: .
#    restart: always
    command: bash -c "npm run build && npm start"
    domainname: misskey.ranranhome.info
    environment:
      NODE_ENV: "production"
    ports:
      - "7000:3000"
    networks:
      - external_network
      - internal_network
    volumes:
      - ./config:/misskey/.config
    depends_on:
      - mongodb
      - redis
#    links:
#      - mongodb
#      - redis

  redis:
#    restart: always
    image: redis:4.0-alpine
    ports:
      - "6379:6379"
    networks:
      - internal_network
### Uncomment to enable REDIS persistance
#    volumes:
#      - ./redis:/data

  mongodb:
#    restart: always
    image: mongo:3.7-jessie
    ports:
      - "27017:27017"
#    environment:
#      - 'MONGODB_USER=misskey'
#      - 'MONGODB_PASS=misskey'
    networks:
      - internal_network
### Uncomment to enable MongoDB persistance
#    volumes:
#      - ./mongodb:/data

networks:
  external_network:
    external:
      name: external_bridge
  internal_network:
    internal: true
